[package]
name = 'rsahmi'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = ['staticlib']
name = 'rsahmi'

[dependencies]
extendr-api = '*'
crossbeam-channel = { version = "*" }
memchr = { version = "*" }
aho-corasick = { version = "*" }
ahash = { version = "*" }
pprof = { version = "0.14", optional = true, features = ["flamegraph"] }

[features]
bench = ["dep:pprof"]

[lints.clippy]
needless_late_init = "allow"
