[package]
name = 'rsahmi'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = ['staticlib']
name = 'rsahmi'

[dependencies]
extendr-api = '*'
noodles-fasta = { version = "*" }
noodles-fastq = { version = "*" }
crossbeam-channel = { version = "*" }
memchr = { version = "*" }
aho-corasick = { version = "*" }

[lints.clippy]
needless_late_init = "allow"
